import { ClientProviders } from "@/providers/ClientSide";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";

import Header from "./../components/Layout/Header";
import Footer from "./../components/Layout/Footer";
import classNames from "classnames";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames("bg-dark-blue", poppins.className)}>
        <Header />
        <ClientProviders>{children}</ClientProviders>
        <Footer />
      </body>
    </html>
  );
}
